// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace web_api.Data.AppDb.Model
{
    public partial class Cartera
    {
        [Key]
        public int CarteraId { get; set; }
        public int? ProductoId { get; set; }
        public int? CuentaId { get; set; }
        [Column(TypeName = "decimal(20, 6)")]
        public decimal MontoTotal { get; set; }
        public int Cantidad { get; set; }

        [ForeignKey(nameof(CuentaId))]
        [InverseProperty("Cartera")]
        public virtual Cuenta Cuenta { get; set; }
        [ForeignKey(nameof(ProductoId))]
        [InverseProperty("Cartera")]
        public virtual Producto Producto { get; set; }
    }
}