// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace web_api.Data.AppDb.Model
{
    public partial class Cuenta
    {
        public Cuenta()
        {
            Cartera = new HashSet<Cartera>();
        }

        [Key]
        public int CuentaId { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50)]
        public string Numero { get; set; }
        public int? ClienteId { get; set; }

        [ForeignKey(nameof(ClienteId))]
        [InverseProperty("Cuenta")]
        public virtual Cliente Cliente { get; set; }
        [InverseProperty("Cuenta")]
        public virtual ICollection<Cartera> Cartera { get; set; }
    }
}