// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace web_api.Data.AppDb.Model
{
    public partial class Precio
    {
        [Key]
        public int PrecioId { get; set; }
        public int? ProductoId { get; set; }
        [Column(TypeName = "decimal(20, 6)")]
        public decimal Valor { get; set; }

        [ForeignKey(nameof(ProductoId))]
        [InverseProperty("Precio")]
        public virtual Producto Producto { get; set; }
    }
}