// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace web_api.Data.AppDb.Model
{
    public partial class Producto
    {
        public Producto()
        {
            Cartera = new HashSet<Cartera>();
            Precio = new HashSet<Precio>();
        }

        [Key]
        public int ProductoId { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }

        [InverseProperty("Producto")]
        public virtual ICollection<Cartera> Cartera { get; set; }
        [InverseProperty("Producto")]
        public virtual ICollection<Precio> Precio { get; set; }
    }
}